3scale/kourier

- deploy/kourier-knative.yaml
- pkg/envoy/envoy.go
* Adds kourier-knative.yaml with all the required to deploy kourier integration with knative
* Changes default listening port of Envoy listener_0 to 8080
> Basic deployment yaml for kourier with knative

- pkg/envoy/envoy.go
Closes #17 
For now it just outputs to stdout using the standard format. There are many options that we can explore in the future: https://www.envoyproxy.io/docs/envoy/v1.11.1/configuration/access_log
> Add access logs

- Makefile
- cmd/kourier/main.go
- pkg/envoy/envoy.go
- pkg/knative/knative.go
- pkg/kubernetes/kubernetes.go
* Removes watchers for service.
* Adds watcher for ClusterIngress.
* Adds support for creating an envoy Snapshot from a ClusterIngress object.
> Use ClusterIngress instead of Service

- Makefile
- cmd/kourier/main.go
- deploy/kourier-knative.yaml
- utils/setup.sh
* Deploys a kubernetes cluster in docker (k3s with k3d)
* Deploys knative 0.9.0 
* Builds a new kourier container image and copies it into the k3s cluster (no remote registry needed). 
* Exposes kourier 8080 port locally.
> Allows to setup a local knative + kourier environment.

- pkg/envoy/envoy.go
Closes #21 
Also, there's a commit that cleans up a bit all the code that instantiates routes. I think we'll need to extract Envoy structures like routes into their own files, but for now it's OK I think.
> Route timeouts

- Makefile
- pkg/envoy/caches.go
- pkg/envoy/caches_test.go
- pkg/envoy/envoy.go
This PR adds unit tests for Ingresses with traffic splits. There are a couple of things that I needed to do first:
- Create a new target in the Makefile so we can run unit and integration tests separately.
- Split the logic in the Envoy package. All the logic to generate caches has been extracted to `caches.go`. That allows us to test separately just the process of creating all the caches needed for an Envoy config snapshot.
We'll need to add more unit tests, but before doing so, I wanted to agree on the way we are going to test this. That's why I just added one test.
> Add test for Ingress with traffic split

- Dockerfile
This PR changes the Dockerfile so it only downloads the dependencies when there have been changes in `go.mod` or `go.sum`.
> Dockerfile: cache downloaded deps

- .circleci/config.yml
- Makefile
- utils/setup-circleci.sh
This PR adds a basic integration with CircleCI. There's room for improvement. For example, we could cache the dependencies, docker images, etc, but I think it's good enough for a first version.
This fails because for some reason, I'm not able to create Knative servings in the k3s cluster deployed in Circle. I've seen that creating servings fails both in our code and with `kubectl`. I'll keep investigating.
> Add initial basic config for CircleCI

- cmd/kourier/main.go
- pkg/knative/knative.go
- pkg/kubernetes/kubernetes.go
Minor change. By using empty structs we signal that we do not care about the values.
> Use empty structs in watcher channels

- pkg/envoy/caches.go
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/websocket.html?highlight=upgrades#websocket-and-http-upgrades
With this we can pass the e2e tests from knative serving: 
```
--- PASS: TestWebSocket (5.11s)
--- PASS: TestWebSocketViaActivator (8.11s)
```
> Adds websocket upgrade support

- pkg/envoy/caches.go
This allows kourier to handle gRPC authority with port and without. 
Related to:
* envoy issue 886
* envoy issue 8305
> Add a duplicate of the host with a port wildcard to virtualhosts due to gRPC authority bug

- cmd/kourier/main.go
- deploy/knative_e2e_tests/kourier-istio-system.yaml
- pkg/envoy/caches.go
- pkg/knative/knative.go
- pkg/kubernetes/kubernetes.go
Improvements to route visibility:
- Define external/internal services for kourier
- Adds new domains based on "routeName+namespace"
- Adds deploy scripts for passing the e2e tests of knative serving.
> Internal routes e2e 

- pkg/envoy/caches.go
- test/integration_test.go
We'll need to investigate why they're not marked as "internal" in the Ingress
> Treat hosts of the default domain as internal

- cmd/kourier/main.go
- pkg/knative/knative.go
This PR introduce the changes needed to only work with the Ingresses and clusterIngresses that are annotated with Kourier's ingress class (introduced in #65 and #66)
The first commit is a minor refactor that makes the change easier.
> Work only with IngressAccessors annotated with Kourier's IngressClass

- cmd/kourier/main.go
- conf/envoy-bootstrap.yaml
- deploy/knative_e2e_tests/kourier-istio-system.yaml
- deploy/kourier-knative.yaml
- utils/setup-circleci.sh
- utils/setup.sh
Splits 3scale kourier POD into two new PODS:
* 3scale-kourier-gateway: Contains the Envoy container
* 3scale-kourier-control: Contains the Kourier control plane container.
> Split Kourier POD into control plane and data plane

- README.md
- docs/knative_e2e_tests.md
This PR adapts the instructions in the README and in `docs/knative_e2e_tests` to take into account the new pods introduced in #68
> Adapt instructions to the new pods

- deploy/knative_e2e_tests/kourier-istio-system.yaml
A missing `---` was causing the istio-ingressgateway Service to not get created when applying this yaml via `oc apply`.
> Fix missing istio-ingressgateway Service in istio yaml

- deploy/knative_e2e_tests/kourier-istio-system.yaml
- deploy/kourier-knative.yaml
When fronted by OpenShift Routes and the OpenShift Serverless
operator, a port name of 'http2' is expected so that the OpenShift
Route sends traffic to the appropriate port.
This should fix a large number of the failing tests when used with the
OpenShift Serverless operator.
> Add a port name of 'http2' to kourier Services

- deploy/knative_e2e_tests/kourier-istio-system.yaml
- deploy/kourier-knative.yaml
* Minor improvements like keepAlive
* Reduced timeout
> Remove deprecated options from envoy bootstrap config

- pkg/envoy/caches.go
- pkg/envoy/http_connection_manager.go
- pkg/envoy/http_connection_manager_test.go
- pkg/envoy/listener_test.go
Extracts the instantiation of `HttpConnectionManager` to its own file to make the code more readable and also to be able to test it in isolation.
> Refactor: extract HttpConnectionManager

- CHANGELOG.md
Same format as in https://keepachangelog.com/en/1.0.0/
> CHANGELOG: add links for versions

- pkg/envoy/caches.go
- pkg/envoy/cluster_cache.go
- pkg/envoy/cluster_cache_test.go
This PR extracts the cluster cache introduced in #91 . The PR also adds tests for the cache and also an explanation of why it is needed. @jmprusi please let me know if you find that explanation clear enough.
> Extract and test ClusterCache

- pkg/envoy/envoy.go
We were logging an error when trying to update an ingress that no longer exists. This is not really an error, it could happen if the ingress was deleted while running the loop to update the config.
I noticed this error while running the "TestRouteVisibilityChanges" test of the Knative e2e suite.
> Change incorrect error message

- Dockerfile.gateway
- deploy/knative_e2e_tests/kourier-istio-system.yaml
- deploy/kourier-knative.yaml
We check that the gateway has been initialized with a kourier config before marking it ready.
> Adds readiness probes to the gateway container

- pkg/envoy/caches.go
- pkg/envoy/caches_test.go
- pkg/envoy/listener_test.go
- pkg/kubernetes/kubernetes.go
The private endpoints object is solely for use in Knative Serving internal systems. The activator for example uses it to hit pods directly, the autoscaler to scrape metrics. Ingress should always go via the public endpoints as that is what Knative uses to control if requests flow via the activator or not.
> Only route the public endpoints object of a revision.

- utils/setup-circleci.sh
"-n" no longer works in the "microk8s.ctr" command. It returns this error when running in circleCI: "ctr: Cannot use two forms of the same flag: n namespace"
> Fix CircleCI setup script

- docs/generated_envoy_config.md
This PR contains a document that describes how we generate Envoy configs from Knative and Kubernetes objects.
> Add doc that explains how configs are generated

- pkg/config/config.go
- pkg/knative/knative.go
- pkg/reconciler/ingress/ingress.go
- pkg/reconciler/ingress/reconciler.go
We were reacting to all changes in ingresses. This PR changes that so we only react to events produced by those ingresses that have the Kourier ingress class.
> Push reconciler events for ingresses only when their ingress class is Kourier

- pkg/envoy/caches.go
- pkg/knative/ingress.go
- pkg/knative/ingress_test.go
This PR extracts all the logic to work with Knative ingresses into its own file. It also adds some unit tests.
I think this change helps us to better organize things, because now in the knative package we have "ingress" and "ingress_rule", which are the Knative entities that we need to work with. We'll no longer have a generic "knative" file.
> Extract Ingress functionality into its own file

- go.mod
- go.sum
- pkg/envoy/caches.go
- pkg/envoy/envoy.go
- pkg/envoy/http_connection_manager.go
- pkg/envoy/http_connection_manager_test.go
- pkg/envoy/listener.go
- pkg/envoy/listener_test.go
This PR, fixes those deprecations:
* AccessLog
* TLSContext
* HTTPManager parameters
I had to update the envoy go control plane to the latest available version, v0.9.1.
> update reprecated envoy config parameters

- Dockerfile.gateway
- deploy/knative_e2e_tests/kourier-istio-system.yaml
- deploy/kourier-knative.yaml
* Removes the installation of curl from the gateway dockerfile
* Uses netcat to do the http healthcheck instead of curl
> Use envoy v1.12.1 to match the current go-control-plane version

- pkg/envoy/caches.go
- pkg/envoy/caches_test.go
- pkg/envoy/envoy.go
- pkg/envoy/generator.go
- pkg/envoy/generator_test.go
- pkg/knative/ingress.go
- pkg/reconciler/ingress/ingress.go
- pkg/reconciler/ingress/reconciler.go
Currently, we are doing a full resync of the config every time we receive an event. We can improve that.
This PR is a first step. It refreshes only parts of the config when an ingress is deleted and also, sets up some structures to make it easier to do similar things for example when an ingress is modified.
> Avoid doing a full resync when an ingress is deleted

- pkg/envoy/caches.go
- pkg/envoy/caches_test.go
- pkg/envoy/generator.go
- pkg/reconciler/ingress/reconciler.go
This PR continues the work started in #125 
Instead of generating the whole Envoy config when there's a change in an ingress, or when an ingress is added, this PR makes some changes so only the part of the config that belongs to that ingress is generated without modifying the rest.
> Update just the modified/added ingress in the config

- pkg/reconciler/ingress/ingress.go
This PR:
- Ensures that the Caches structure is initialized when instantiating the reconciler. That's so we do not have to worry about whether it's nil or not in the rest of the code.
- Ensures that a full resync is the first event triggered.
> Improve Caches initialization in the reconciler

- go.mod
- go.sum
- pkg/envoy/envoy.go
- pkg/envoy/generator.go
- pkg/envoy/generator_test.go
- pkg/reconciler/ingress/ingress.go
- pkg/reconciler/ingress/reconciler.go
By using the knative tracker package we can track the endpoints that
relate to an ingress. When there's a change to that endpoints object, we
get an event for the specific Ingress that owns it.
> Use knative.dev/pkg/tracker for Endpoints

- pkg/envoy/generator.go
- pkg/knative/ingress.go
- pkg/knative/ingress_test.go
- pkg/reconciler/ingress/reconciler.go
Just some things I noticed while scanning the code again.
1. We don't need to deal with "Route" shenanigans at all I think? Our central piece of information should always be Ingress. They are probably named the same anyway so 🤷‍♂ , might as well just ditch the helpers.
2. We can determine if something exists or not by using the `IsNotFound` check on the error returned by a GET operation. This redoes some bits of the reconciler setup to be able to just do one GET for the whole cycle.
> Clean up some unnecessary helper functions.

- Makefile
Adds the -race arg to the test commands in the Makefile.
We'll need this for #133 which performs work in several go-routines.
> Test with -race arg

- go.mod
- pkg/envoy/caches.go
- pkg/envoy/envoy.go
- pkg/envoy/generator.go
- pkg/reconciler/ingress/controller.go
- pkg/reconciler/ingress/ingress.go
- pkg/reconciler/ingress/status.go
* Handle Ingresses readiness asynchronously. 
* Creates one path for each ingress in the internal kourier gateway service. We can track ingresses readiness individually.
We should create a new release before merging this PR to test the current changes. Then, a new Release with this PR merged so we can identify what breaks what.
> Ingress statusManager

- pkg/generator/caches.go
- pkg/generator/caches_test.go
- pkg/generator/cluster_cache.go
- pkg/generator/cluster_cache_test.go
- pkg/generator/generator.go
Makes some changes in the cluster cache to allow setting expirations when deleting an ingress.
> Rework cluster cache to allow expires

- pkg/reconciler/ingress/status.go
Simply deletes a constant and a struct that are not used.
> Deleted unused code in the status prober

- conf/envoy-bootstrap.yaml
- deploy/knative_e2e_tests/kourier-istio-system.yaml
- deploy/kourier-knative.yaml
* Envoy admin now listens to an internal UNIX socket.
* Exposes the envoy socket through a listener that only allows "safe" commands
> Expose an stats endpoint at port 9000

- pkg/envoy/xds_server.go
- pkg/reconciler/ingress/status.go
Makes some structs In the envoy and status packages private.
I've left the generator package for later because I think we might need to split it.
> Avoid exposing structs unnecessarily

- deploy/kourier-knative.yaml
Relying on native tools may have caused a leak and eventual failure in
long running Pod.
Use built in http probe as opposed to exec and drop the need for
external tooling.
@jmprusi should resolve #158
> Moves readiness probe to http instead of exec

- deploy/kourier-knative.yaml
As per title, this patch replaces ClusterIP with LoadBalancer for kourier-external service.
Current configuration does not pass e2e by default. Please refer to  https://github.com/knative/serving/pull/6450.
> Use LoadBalancer instead of ClusterIP for kourier-external

- pkg/knative/ingress.go
- pkg/reconciler/ingress/status.go
This patch adds a condition to update ingress status when status field is updated or not ready.
Currently the ingress is not reconciled when it is deleted.
Fixes https://github.com/3scale/kourier/issues/164
> Update ingress status when status field is updated or not ready

- pkg/envoy/headers.go
In Knative serving, headers are set instead of appended. See this: https://github.com/knative/serving/pull/6366
This fixes a couple of tests that were failing in the Knative upstream:
- `test/conformance/ingress.TestPostSplitSetHeader`
- `test/conformance/ingress.TestPreSplitSetHeaders`
> Set headers instead of appending them

- deploy/knative_e2e_tests/kourier-istio-system.yaml
- deploy/kourier-knative.yaml
- docs/knative_e2e_tests.md
- pkg/knative/ingress.go
Simplifies a bit the deployment. The "kourier" and "kourier-external" services are equivalent. Defining just one is enough.
> Define just one external service

- README.md
- deploy/kourier-knative.yaml
- docs/knative_e2e_tests.md
- utils/setup-circleci.sh
- utils/setup.sh
This changes the kourier namespace to `kourier-system`. Until now it was using the same as knative (`knative-serving`). There's no reason to do that. Also, with this PR we'll no longer need to patch the deployment yaml in Knative (https://github.com/knative/serving/blob/25658ef8c7b1bee4e0996566833e2ced22cdef9b/third_party/kourier-latest/download-kourier.sh#L46).
> Change kourier namespace

- deploy/kourier-knative.yaml
- pkg/envoy/http_connection_manager.go
- pkg/envoy/listener.go
- pkg/envoy/listener_test.go
- pkg/generator/caches.go
- pkg/generator/caches_test.go
- pkg/generator/generator.go
An ingress can have a TLS field. See this example:
https://github.com/knative/serving/blob/83e72f0b1ee0508b2a4ce2c487ba571cffe90dde/test/conformance/ingress/tls_test.go#L59
That's a test from the Knative serving repo that was failing when using Kourier because we were ignoring that field. This PR fixes it.
SNI routing has been implemented as described in the Envoy docs: https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/sni.html
> Add support for ingress TLS

- deploy/kourier-knative.yaml
Without this, the ["TestIngressTLS" test of Knative Serving](https://github.com/knative/serving/blob/83e72f0b1ee0508b2a4ce2c487ba571cffe90dde/test/conformance/ingress/tls_test.go#L31) passes locally, but it fails in the upstream.
> Expose http and https in same service

- pkg/reconciler/ingress/status.go
In some situations an ingress can be modified and while it will remain
marked as Ready, the generation and the observer generation will not
match, marking the ksvc as not ready.
This commit solves this situation by fixing a problem in the
statusmanager logic.
> Fix statusmanager logic for marking ready an ingress

- pkg/knative/ingress.go
The comment no longer applies. What's mentioned there is now handled by the status prober.
> Delete old TODO that no longer applies

- pkg/generator/generator.go
This PR is needed to pass one of the Knative serving tests that are currently failing when running with Kourier: `TestPerKsvcCert_localCA`.
The secrets referenced in the TLS section of an ingress might not be available when the ingress is created. What we need to do in that case is propagate the error to the reconciler, so the event is retried later until the secret is created.
> Propagate err to reconciler when TLS secret not available

- pkg/generator/generator.go
The `TestUpdate` test is flaky because at the end of the test some requests return 404. See https://testgrid.knative.dev/serving#kourier-stable
This patch should fix the issue.
> Avoid generating Envoy configs from ingresses without routes

- pkg/envoy/http_connection_manager.go
- pkg/generator/generator.go
This PR simply moves the code to instantiate an HTTPConnectionManager with RDS to the Envoy package. That code is Envoy specific, so it should be in the envoy package to be consistent with the rest of the codebase.
> Refactor: Move helper to instantiate HTTPConnManager with RDS

- pkg/envoy/cluster.go
- pkg/envoy/cluster_test.go
- pkg/envoy/headers.go
- pkg/envoy/lb_endpoint.go
- pkg/envoy/route.go
- pkg/envoy/weighted_cluster.go
- pkg/generator/caches.go
- pkg/generator/caches_test.go
- pkg/generator/cluster_cache.go
- pkg/generator/generator.go
- pkg/generator/generator_test.go
- pkg/knative/ingress_rule.go
- pkg/knative/ingress_rule_test.go
- pkg/reconciler/ingress/controller.go
I hope this disentangles the use of pointer vs. no-pointer a little.
When to use a pointer? For "foreign" objects (like the Envoy stuff) I usually look up their API and see if the functions are defined on the respective pointer receiver. If so, you probably should use pointers in your code for these resources throughout.
> Remove unnecessary pointer conversions and move them to their constructors.

- pkg/generator/caches.go
- pkg/generator/generator.go
- pkg/generator/status_vhost.go
This PR extracts the generation of the status virtual host into its own file. It's a piece that can be understood and tested in isolation, so I think it's better to have it in a separate file. While at it, I added some documentation.
This is part of a refactor effort to make the generator module easier to understand. More PRs coming in the next days :smile:
> refactor: extract generation of the status virtual host

- deploy/kourier-knative.yaml
related to: https://github.com/openshift-knative/serverless-operator/commit/27a58f4c1800f952effe64d27feaa76e9ae3b2fb
> Use http2 instead of http as the port names

- pkg/generator/caches.go
- pkg/generator/caches_test.go
- pkg/generator/cluster_cache.go
- pkg/generator/cluster_cache_test.go
- pkg/generator/generator.go
- pkg/generator/generator_test.go
- pkg/reconciler/ingress/controller.go
- pkg/reconciler/ingress/ingress.go
To enable set into the configmap "config-logging" in the kourier-system namespace the zap-logger-config: 
```yaml
data:
zap-logger-config: |
{
"level": "debug",
"development": false,
"outputPaths": ["stdout"],
"errorOutputPaths": ["stderr"],
"encoding": "json",
"encoderConfig": {
"timeKey": "ts",
"levelKey": "level",
"nameKey": "logger",
"callerKey": "caller",
"messageKey": "msg",
"stacktraceKey": "stacktrace",
"lineEnding": "",
"levelEncoder": "",
"timeEncoder": "iso8601",
"durationEncoder": "",
"callerEncoder": ""
}
}
```
> Adds debug logging and named loggers

- pkg/generator/caches.go
- pkg/generator/cluster_cache.go
- pkg/reconciler/ingress/controller.go
- Reduce the times for cache expiration and Cleanup.
> Refresh config on cluster eviction

- pkg/config/config.go
- pkg/knative/ingress.go
- pkg/reconciler/ingress/controller.go
- pkg/reconciler/ingress/status.go
Fetching the pods directly is fine in general but causes us to have to doublecheck pod readiness and availability of an IP. This spares us reimplementing those checks.
> Fetch gateway ports via the service to guarantee base readiness.

- deploy/kourier-knative.yaml
AFAICT, these are all defaults anyway and not needed to be spelled out specifically. Especially the scheduler bit breaks on my local dev environment.
> Remove a few redundant values from the deployment manifest.

- pkg/knative/ingress.go
- pkg/reconciler/ingress/controller.go
- pkg/reconciler/ingress/ingress.go
- pkg/reconciler/ingress/status.go
Trying to update status outside of the usual reconcile flow will lead to conflicts where it's unclear how and when those conflicts will be retried.
> Update ingress status in the reconcile cycle.

- pkg/generator/caches.go
- pkg/generator/caches_test.go
- pkg/generator/generator.go
- pkg/generator/ingress_translator.go
- pkg/generator/ingress_translator_test.go
- pkg/reconciler/ingress/controller.go
- pkg/reconciler/ingress/ingress.go
Don't merge yet. Let's merge the pending PRs first to avoid conflicts.
This PR extracts all the logic that translates an ingress into the Envoy data structures that we need. Apart from making that part easier to test and understand, it simplifies the cache and makes it less error prone, because now, all the info for an ingress is added at once. It also helps us to avoid sending many params from the reconciler to the generator.
> Refactor generator

- pkg/reconciler/ingress/status.go
If no gateway pods are up (yet), which happens on a system upgrade, we should retry the reconcilation until we finally find a gateway pod. Returning an error effectively does that. It adds rate limiting too.
> Retry if no gateway pods can be found.

- pkg/generator/ingress_translator.go
- pkg/generator/ingress_translator_test.go
- pkg/reconciler/ingress/controller.go
- vendor/go.uber.org/zap/internal/ztest/doc.go
- vendor/go.uber.org/zap/internal/ztest/timeout.go
- vendor/go.uber.org/zap/internal/ztest/writer.go
- vendor/go.uber.org/zap/zaptest/doc.go
- vendor/go.uber.org/zap/zaptest/logger.go
- vendor/go.uber.org/zap/zaptest/testingt.go
- vendor/go.uber.org/zap/zaptest/timeout.go
- vendor/go.uber.org/zap/zaptest/writer.go
- vendor/knative.dev/pkg/logging/testing/util.go
- vendor/modules.txt
No logger has been passed into the generator, causing it to panic with a nil pointer as soon as something went wrong.
> Actually pass a logger into the generator.

- pkg/generator/caches.go
- pkg/generator/generator.go
- pkg/generator/ingress_translator.go
- pkg/generator/ingress_translator_test.go
This PR uses the ingress name, the namespace, and the path in route names to ensure uniqueness. We were using an "index" before based on the number of ingresses stored in the current config. Apart from complicating the code a bit, using an index alone without taking into account the namespace does not ensure uniqueness.
> Ensure uniqueness in route names

- pkg/envoy/callbacks.go
- pkg/envoy/xds_server.go
- pkg/reconciler/ingress/controller.go
- vendor/github.com/golang/glog/LICENSE
- vendor/github.com/golang/glog/README
- vendor/github.com/golang/glog/glog.go
- vendor/github.com/golang/glog/glog_file.go
- vendor/knative.dev/pkg/test/README.md
- vendor/knative.dev/pkg/test/e2e_flags.go
- vendor/knative.dev/pkg/test/kube_checks.go
- vendor/knative.dev/pkg/test/spoof/spoof.go
- vendor/knative.dev/pkg/test/tinterface.go
- vendor/modules.txt
By using callbacks we detect when a envoy instance returns an error when trying to load the new snapshot and retry.
> On xds callback error trigger a new global resync

- pkg/generator/caches.go
It was probably needed at some point and we forgot to delete it.
> Delete unnecessary array instantiation in Caches

- pkg/generator/generator.go
- pkg/generator/ingress_translator.go
- pkg/generator/ingress_translator_test.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
- vendor/knative.dev/pkg/reconciler/testing/actions.go
- vendor/knative.dev/pkg/reconciler/testing/clock.go
- vendor/knative.dev/pkg/reconciler/testing/context.go
- vendor/knative.dev/pkg/reconciler/testing/events.go
- vendor/knative.dev/pkg/reconciler/testing/generate_name_reactor.go
- vendor/knative.dev/pkg/reconciler/testing/hooks.go
- vendor/knative.dev/pkg/reconciler/testing/reactions.go
- vendor/knative.dev/pkg/reconciler/testing/sorter.go
- vendor/knative.dev/pkg/reconciler/testing/stats.go
- vendor/knative.dev/pkg/reconciler/testing/table.go
- vendor/knative.dev/pkg/reconciler/testing/tracker.go
- vendor/knative.dev/pkg/reconciler/testing/util.go
- vendor/knative.dev/pkg/system/testing/names.go
- vendor/modules.txt
There are a ton of "ingress with no routes" errors that fix themselves because the trackers actually pick up endpoints being added/changed eventually and thus we start creating the respective routes.
On the other hand, we should fail reconcilation immediately if the tracker can't track properly or if we can't fetch resources for reasons different than "not found".
> Reduce errors that fix themselves and make fatal errors more explicit.

- pkg/envoy/ext_authz.go
- pkg/envoy/http_connection_manager.go
- pkg/reconciler/ingress/controller.go
Not too important from a performance view probably, but this signals that those 2 fields can be initialized when the ext authz is nstantiated rather than calculated every time.
> Initialize cluster and HTTP filter when instantiating the external authz

- Makefile
So the 'fmt' target appears when running 'make help'.
> Add missing "#" in Makefile
