pkg/envoy/envoy.go
=> Add support for ClusterIngress retries

utils/setup.sh
=> Forward admin port in local setup

cmd/kourier/main.go, pkg/kubernetes/kubernetes.go
To avoid problems like parsing them multiple times.
=> Move parsing of flags to init()

Makefile, go.mod, go.sum, test/helpers.go, test/integration_test.go, utils/setup.sh
Adds a basic integration test and a new Makefile target: `test-integration`
=> First basic integration test

pkg/envoy/envoy.go
* Now there are only a few initial requests hitting the activator, once a revision POD is booted-up, we stop sending traffic to the activator POD, this is done by lowering the priority of the Activator endpoint.
* Fix for the status update
=> Use the activator endpoint only when there's no container ready

pkg/knative/knative.go, pkg/kubernetes/kubernetes.go
=> Wait until Informer caches are sync'd

deploy/kourier-knative.yaml, pkg/envoy/caches.go, pkg/envoy/caches_test.go, pkg/envoy/listener.go, pkg/envoy/listener_test.go, pkg/kubernetes/kubernetes.go, utils/setup.sh
Fixes #20 
I took the opportunity to refactor a bit. I extracted the code that generates Envoy listeners into its own file.
=> TLS support

pkg/envoy/envoy.go, pkg/knative/knative.go
It sets the internal domain. It's the same that istio does.
=> Set load balancers when updating Ingress status

cmd/kourier/main.go, pkg/knative/knative.go, pkg/kubernetes/kubernetes.go
The work queue contributes to reduce the number of unnecessary events that we receive because it does not store duplicated objects.
This is a better fix for #10 than the one we merged some days ago.
=> Use a work queue for events

pkg/envoy/caches.go
=> Refactor: extract ingressRuleIsExternal() in caches module

pkg/envoy/caches.go, pkg/knative/ingress_rule.go, pkg/knative/ingress_rule_test.go
This PR extracts and tests all the internal/external domains logic of Knative's ingress rules.
=> Extract Knative's IngressRule logic

README.md, docs/knative_e2e_tests.md
Added more info on how to deploy kourier & knative without Istio.
=> Improve Kourier installation documentation.

utils/setup-circleci.sh, utils/setup.sh
Various fixes to remove the shellcheck warnings.
=> Fix shellcheck linting issues 

Dockerfile.gateway, Makefile, deploy/knative_e2e_tests/kourier-istio-system.yaml, deploy/kourier-knative.yaml, utils/setup-circleci.sh, utils/setup.sh
For now, a simple wrapper on top of the already existing envoy docker image to run envoy as non-root user
=> New kourier-gateway image.

.circleci/config.yml, Makefile, cmd/kourier/main.go, pkg/envoy/caches.go, pkg/envoy/caches_test.go, pkg/envoy/envoy.go, pkg/envoy/listener.go, pkg/envoy/listener_test.go, pkg/knative/ingress_rule.go, pkg/knative/ingress_rule_test.go, pkg/knative/knative.go, pkg/kubernetes/kubernetes.go, test/helpers.go, test/integration_test.go
Suggesting to use [goimports](https://github.com/golang/tools/tree/master/cmd/goimports) tool for formatting and add a check to be run on CircleCI (will likely need to be installed in the image)
=> Run goimports across project

pkg/knative/knative.go
Small "fix" for a duplicated line
=> Remove duplicated status.ObservedGeneration

CHANGELOG.md, deploy/knative_e2e_tests/kourier-istio-system.yaml, deploy/kourier-knative.yaml
Docker image already generated and pushed to quay.
=> Release 0.2.1

cmd/kourier/main.go, pkg/envoy/caches.go, pkg/envoy/caches_test.go, pkg/envoy/envoy.go, pkg/knative/knative.go
As in knative serving >0.9 the ClusterIngresses CRD is not created anymore.
=> Removes support for ClusterIngresses Objects

test/helpers.go, test/integration_test.go
The service will be ready before the Ingress, but we should not try to make requests until the ingress is ready.
=> test/integration: wait for Ingress instad of Service

deploy/knative_e2e_tests/kourier-istio-system.yaml, deploy/kourier-knative.yaml
They're not needed and cause problems.
=> Remove status from deployment yamls

pkg/knative/knative.go
=> Remove last occurrence of IngressAccessor and unneeded type assertions.

pkg/reconciler/ingress/ingress.go
Similar to the previous PR (#117) but for endpoints.
=> Filter endpoint events and make sure there's a config at boot

pkg/envoy/xds_server.go, pkg/generator/caches.go, pkg/generator/generator.go, pkg/reconciler/ingress/controller.go, pkg/reconciler/ingress/ingress.go
Handle errors to enqueue failed events
=> Handle errors to enqueue failed events

.circleci/config.yml
To have "master" images (control and gateway) automatically updated.
=> Push images when building from master in CircleCI

pkg/reconciler/ingress/controller.go, pkg/reconciler/ingress/ingress.go
This patch adds some error handling to avoid missing errors.
=> Handle error returned

pkg/generator/caches.go
Without this we can generate routes that point to non-existing clusters. That causes some "no_cluster" errors in Envoy and the "TestUpdate" in the Knative serving test suite fails sometimes.
Ref: https://github.com/knative/serving/blob/f6da03e5dfed78593c4f239c3c7d67c5d7c55267/tes
=> Validate clusters in route configs

pkg/config/config.go, pkg/envoy/cluster.go, pkg/envoy/http_connection_manager.go, pkg/envoy/http_connection_manager_test.go, pkg/envoy/listener_test.go, pkg/envoy/route.go, pkg/envoy/xds_server.go, pkg/generator/caches.go, pkg/generator/generator.go, pkg/generator/generator_test.go, pkg/knative/ingress_rule.go, pkg/reconciler/ingress/controller.go, pkg/reconciler/ingress/ingress.go, pkg/reconciler/ingress/status.go, test/integration_test.go
The statusProber thing is potentially kinda bad even, if it's used at all 😅
=> Fix a few nits throughout the code.

pkg/generator/generator.go
If the endpoint object does not exists, we break the loop and not add the tracking to associate
the ingress to the endpoint.
=> Track ingress -> endpoint relationship before break

Dockerfile.gateway, Makefile, utils/setup-circleci.sh, utils/setup.sh
Uses maistra envoy for local-setup and circle ci jobs.
=> Use maistra envoy 1.11.0 

.circleci/config.yml
No longer needed. We switched to maistra.
=> circleci: do not update the gw image
